"""Add latitude and longitude to Service model

Revision ID: f7f5621b5687
Revises: 6e47ab5df2db
Create Date: 2025-07-08 02:05:11.889859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7f5621b5687'
down_revision: Union[str, Sequence[str], None] = '6e47ab5df2db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('services', sa.Column('longitude', sa.Float(), nullable=True))
    op.drop_constraint(op.f('uq_service_name_category'), 'services', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_service_name_category'), 'services', ['name', 'category_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('services', 'longitude')
    op.drop_column('services', 'latitude')
    # ### end Alembic commands ###
